### ISSUE TITLE
Using DD with ajax website

### ISSUE THREAD

**Issue by rightbeatradio** [A5hleyRich/delightful-downloads#102]
Hi, awesome plugin. Been using it for a long time now.

We recently moved over to a new heavily ajaxified website theme. Certain content is now loaded with ajax, including our download shortcodes. 

Now instead of the file download instantly starting, it now tries to open it like a new page and only a blank white screen appears. Nothing ever happens. The download will work if I open the download link in a new window/tab. But without manually opening the download in a new window/tab, there is just a blank white screen.

Is there a way to fix this so that we can continue to use this plugin with out current theme?

Please help, and thanks for all your support for the plugin!
M!ke

http://rightbeatradio.com

**Comment by A5hleyRich** [comment]
This issue has cropped up a few times now. You can try ensuring that download links open in a new tab, as per this topic.

https://wordpress.org/support/topic/opening-in-a-new-tab?replies=9

However, if your theme still hijacks those URLs there's not really a lot we can do and this will be something you would need to take up with the theme author.
