### ISSUE TITLE
Button Class

### ISSUE THREAD

**Issue by termoplus** [A5hleyRich/delightful-downloads#121]
Hello,

Can you please help me to find a template to change the button class?
I know I will lose it after update but I need to change the button class.

thanks

**Comment by A5hleyRich** [comment]
You should add a custom button, as per the docs:

https://delightfuldownloads.com/documentation/custom-buttons/

If you have any issues please raise them on the support forums, GitHub is for bugs only:

https://wordpress.org/support/plugin/delightful-downloads
