### ISSUE TITLE
Spanish Language

### ISSUE THREAD

**Issue by VirtualW** [A5hleyRich/delightful-downloads#122]
Attached Spanish language.I hope this helps.
The only thing that not translates is the "Download" button (still appears in English even when translated the .mo file).
Thanks for your great plugin. I searched lot a plugin like yours.
I wanted to thank at least with this :-)

https://www.dropbox.com/s/29mnwg8sz6gh8jt/delightful-downloads-es_ES.zip?dl=0

**Comment by A5hleyRich** [comment]
Thanks @VirtualW. I'll get these added in the next release and look into the download button.

**Comment by A5hleyRich** [comment]
Added to Transfex, will be included in 1.6 release.

**Comment by VirtualW** [comment]
I am glad that it has been helpful! :-)
