### ISSUE TITLE
Russian translation update [enhancement]

### ISSUE THREAD

**Issue by jevgen** [A5hleyRich/delightful-downloads#123]
I updated Russian PO file, fixed several mistakes and completed translation. 
https://www.dropbox.com/s/ejvvbopn2res6b3/for_use_delightful-downloads_delightful-downloads_ru_RU%20%28JC%20edit%29.po.zip?dl=0

**Comment by A5hleyRich** [comment]
Thanks @jevgen!

**Comment by A5hleyRich** [comment]
Added to Transfex, will be included in 1.6 release.

**Comment by jevgen** [comment]
Cheers! I shall follow in Transfex, if they'll allow.
