### ISSUE TITLE
Addon: Limit downloads per day by IP address

### ISSUE THREAD

**Issue by A5hleyRich** [A5hleyRich/delightful-downloads#133]
https://wordpress.org/support/topic/limitation-downloads-from-one-ip?replies=1

**Comment by EddiebNZ** [comment]
Did this issue ever progress? I use Delightful Downloads and being able to restrict daily downloads by Registered User/IP address is the one feature I'd love to have in Delightful Downloads.

**Comment by A5hleyRich** [comment]
I'm afraid not. Delighful Downloads is no longer maintained.
