### ISSUE TITLE
thumbnails and widget

### ISSUE THREAD

**Issue by jaylinski** [A5hleyRich/Delightful-Downloads#57]
hi there! i really like your plugin, it's the only download manager that's easy to use.
i would love to add a 'thumbnail' feature and a widget to display a download in the sidebar.
are you open for pull requests regarding these features?

**Comment by A5hleyRich** [comment]
Hi @jaylinski. They're both on the to-do list, so I'm more than happy for you to implement those features.

**Comment by jaylinski** [comment]
cool, thanks!

**Comment by jaylinski** [comment]
see A5hleyRich/Delightful-Downloads/pull/60 and A5hleyRich/Delightful-Downloads/pull/61
thanks for having a look at it!
