### ISSUE TITLE
Static-File-Server

### ISSUE THREAD

**Issue by DavidSteinbauer** [A5hleyRich/delightful-downloads#58]
I have an issue with the
```
		define("WP_CONTENT_URL", "http://static.domain.com");

```

I get the message because my Donwload links look like 
```
http://static.domain.com/uploads/delightful-downloads/file.pdf
```
```
File doesn't exists!
```

can you fix this for me?

Thank you very much

**Comment by A5hleyRich** [comment]
Hey David,

Sorry for the delay. Looking into this now.

**Comment by A5hleyRich** [comment]
Unable to replicate this issue. By default assets are served via absolute paths, that constant shouldn't have any negative effect.

**Comment by DavidSteinbauer** [comment]
you're right! 
but it has effects on saving the meta_key '_dedo_file_url' to the post_meta data..
please have a try an set WP_CONTENT_URL to a subdomain when uploading a file AFTERWARDS and inserting the shortcode it WP tells you "file doesn't exsits". Files uploaded before are not affected by that!

Trust me!
