### ISSUE TITLE
Downloads not working on Windows server

### ISSUE THREAD

**Issue by aboivin00** [A5hleyRich/delightful-downloads#80]
I have tried everything and the downloads will not open unless you are signed in. I have indicated in each document you do not need to be members as well as turned off all protection. Please help.

**Comment by jaylinski** [comment]
any error message?

**Comment by aboivin00** [comment]
It is an HTTP 500 error I also notice the link is not changing it is
displayed as http://wismoose.org/?ddownload=1335

**Comment by jaylinski** [comment]
500 is an internal server error, do you have access to your php-error-logfile?

**Comment by aboivin00** [comment]
I just took this website on a few months ago and it appears to be very unorganized I'm sure I have access to them if there are any. I can not seem to find them.
Amy

**Comment by jaylinski** [comment]
I'm not that experienced with windows servers (your website runs on a windows machine), so unfortunately I can't tell you where to find the php-logs on your server.
Is there any good reason why you are hosting your wordpress on a windows machine?

**Comment by aboivin00** [comment]
No there really was no good reason I changed from a windows and it works now! Thanks for your help !

**Comment by jaylinski** [comment]
good to hear, glad I could help :)

**Comment by A5hleyRich** [comment]
Was the server running on IIS or Apache do you know?

**Comment by A5hleyRich** [comment]
Tested on Apache under Windows, no issues found. IIS isn't officially supported so closing.
